defaults: &defaults
  working_directory: ~/buildbox
  docker:
    - image: circleci/ruby:2.6.5-stretch-browsers

version: 2.0
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13

      - run:
          name: Login to Docker Registry
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS

      - run:
          name: Build Docker Image
          command: docker build --build-arg ARG_RAILS_MASTER_KEY=$DOCKER_RAILS_MASTER_KEY -t tanngoc93/com.thedogpaws.coupon:latest .

      - run:
          name: Push Docker Image to Docker Registry 
          command: docker push tanngoc93/com.thedogpaws.coupon:latest

workflows:
  version: 2
  build-image:
    jobs:
      - build:
          filters:
            branches:
              only: master